### ISSUE TITLE
Add search feature .

### ISSUE THREAD

**Issue by Arijit-017** [Arijit-017/ISTE-Contribution-React#2]
# Issue: Add Search Feature

## Description

We need to add a search functionality to the project that allows users to search by **GitHub ID** or **Name**. Your task is to create a new component that handles the search operation separately.

## Steps to Contribute

1. **Fork the Repository**
   - Click the `Fork` button at the top right of this repository's page to create a copy of the repo under your GitHub account.

2. **Clone it to Your Local Machine**
   - Open your terminal and use the following command to clone the repo:
     ```bash
     git clone https://github.com/your-username/repo-name.git
     ```

3. **Add a Search Feature**
   - Create a new component in the project dedicated to the search functionality.
   - The search should allow users to search by either **GitHub ID** or **Name**.
   - Ensure the results are dynamically displayed based on the search input.

4. **Push Your Changes**
   - After adding the search feature, commit your changes using:
     ```bash
     git add .
     git commit -m "Added search feature"
     git push origin main
     ```

5. **Create a Pull Request**
   - Head back to the repository on GitHub, and click on `Compare & pull request`. Provide a meaningful description of your changes and create the pull request.

---

Thanks for contributing to this project! We appreciate your effort in adding this feature. 🎉

**Comment by Fixito** [comment]
Hi, I’d like to work on this issue. Could you please assign it to me?
