### ISSUE TITLE
Add Dark Mode Feature

### ISSUE THREAD

**Issue by Arijit-017** [Arijit-017/ISTE-Contribution-React#3]
# Issue: Add Dark Mode Feature

## Description

We need to implement a **Dark Mode** toggle for the application. Your task is to create a dark mode that can be switched on or off by the user. The theme should persist across sessions (store preference locally).

## Steps to Contribute

1. **Fork the Repository**
   - Click the `Fork` button at the top right of this repository's page to create a copy of the repo under your GitHub account.

2. **Clone it to Your Local Machine**
   - Open your terminal and use the following command to clone the repo:
     ```bash
     git clone https://github.com/your-username/repo-name.git
     ```

3. **Add Dark Mode**
   - Implement a dark mode toggle that allows users to switch between light and dark themes.
   - The dark mode should affect the entire application, including backgrounds, text colors, and component styles.
   - Ensure that the dark mode preference is stored using **localStorage** so that it persists even after the page is refreshed or reopened.

4. **Push Your Changes**
   - After adding the dark mode feature, commit your changes using:
     ```bash
     git add .
     git commit -m "Added dark mode feature"
     git push origin main
     ```

5. **Create a Pull Request**
   - Head back to the repository on GitHub, and click on `Compare & pull request`. Provide a meaningful description of your changes and create the pull request.

---

Thank you for contributing! We're excited to see the dark mode feature in action. 🌙✨

**Comment by Snehalgupta-07** [comment]
Hi I can do this can u pls assign it to me

**Comment by Arijit-017** [comment]
Yes, now you can do it.
